{{- if eq .Values.mode "gateway" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skep-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skep-collector.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "skep-collector.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
{{- end }}
